name: Deployment en Google Cloud

on:
  push:
    branches: ['main']
  pull_request:
     branches: ['main']
     types: [opened, synchronize]

jobs:
  Environment:
    runs-on: ubuntu-20.04
    steps:
      - name: Check-skip
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - run: bash script/install-environment.sh
      - run: bash script/install-project.sh
      - run: ls -1
  
  VM_google_cloud:
    runs-on: ubuntu-20.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Actualización del código
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0
      # Identificación en google cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
       # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      # Listamos las VM que tenemos en google cloud
      - name: List VM
        run: gcloud compute instances list
      #Creamos la VM
      - name: Deploy
        run: gcloud compute instances create rick-and-morty-vm-${{ github.sha }} --machine-type=n1-standard-1 --zone=us-central1-a  
       # Listamos las VM que tenemos en google cloud
      - name: List VM
        run: gcloud compute instances list
      # Borramos las VM que tenemos en google cloud
      - name: Delete VM
        run: gcloud compute instances delete rick-and-morty-vm-${{ github.sha }} --zone=us-central1-a
         # Listamos las VM que tenemos en google cloud
      - name: List VM
        run: gcloud compute instances list
  
  